### PR TITLE
idk

### PR DESCRIPTION
**Pull request by Redageddon**

### CODE REVIEW

**Comment by Adrriii** [comment]
I just closed the other PR saying that you needed to split your PR in several ones, please

**Comment by Redageddon** [comment]
do NOT view this on github. view this in some form of editor

**Comment by Adrriii** [comment]
we still need to review everything

**Comment by Adrriii** [comment]
also, the whole code cleanup is unnecessary and mostly even unwanted since we added the editor config. you can revert these

**Comment by Redageddon** [comment]
as you stated it is easy to change, and i dont see why upgrading to dotnet core 3.1, shortening the code, shortening the size, increasing the speed and more would be unwanted.

**Comment by Redageddon** [comment]
i made it better and for some reason you dont want that, why? you arent making it better yourself so someone has to

**Comment by Adrriii** [comment]
I'm only saying that the code cleanup (those tips from the IDE you applied) that is taking a whole lot of lines and obstructing all the "real" changes, are now unwanted (read: unneeded)

The rest can be interesting and that is what we wish to review, but not all at once. Things might not be accepted while some other things could be accepted on the spot.

**Comment by Redageddon** [comment]
thats why i said to not compare them using github

**Comment by Redageddon** [comment]
closed, just put up here to notify that what i did is done.

**Pull request closed without merging**
