### PR TITLE
WIP: Add Comments & Documentation

### PR DESCRIPTION
**Pull request by dustdustinthewind**
https://github.com/PulsarcGame/Pulsarc/issues/37#issuecomment-520693115

> Perhaps use WIP: tag and make a pull request so it would be easier to review code.

Sure thing. 👌

### CODE REVIEW

**Comment by dustdustinthewind** [comment]
I've applied the suggested fixes, they're in https://github.com/PulsarcGame/Pulsarc/pull/42/commits/dd991df3aa7af38a8874af43b2d34a202a3d6897. Thanks Jaan and Adri.

**Comment by dustdustinthewind** [comment]
At this point, I believe I have added comments to most or all of the "important" files. Not like most of the files in the `Pulsarc.UI.Screens.Result.UI` namespace.

Along with more documentation I changed a few things.

> - Removed some old and unnecessary comments.
> - Judge.cs has been given Anchor.Center so it doesn't need to adjust itself.
> - Renamed private "getSkinnable..." methods for clarity.
> - Added a descending sort to SongSelection.cs
> - Moved Anchor enum from TextDisplayElement.cs to Drawable.cs.
> - Anchor.CenterBottom and Anchor.CenterTop have been added to the Anchor enum; relevant switch-case code has been updated.

**Comment by jaanjah** [comment]
@FlyingRabidUnicornPig next time use rebase, so you don't flood the commit history with "Merge branch x to y", only exception to that if you are actually merging to another branch.

**Comment by jaanjah** [comment]
This can still be fixed with squashing. Example: (https://davidwalsh.name/squash-commits-git)

**Comment by dustdustinthewind** [comment]
Thank you for the info!

**Pull request merged**
